package com.saita.hardmodemod.init;

import com.saita.hardmodemod.HardmodeMod;
import com.saita.hardmodemod.HardmodeMod.HardmodeItemGroup;
import com.saita.hardmodemod.blockitems.*;
import com.saita.hardmodemod.items.*;
import com.saita.hardmodemod.items.tools.*;
import com.saita.hardmodemod.items.armors.*;
import com.saita.hardmodemod.items.repeaters.*;
import com.saita.hardmodemod.util.enums.HardmodeArmorMaterial;
import com.saita.hardmodemod.util.enums.HardmodeItemTier;

import net.minecraft.inventory.EquipmentSlotType;
import net.minecraft.item.Food;
import net.minecraft.item.Item;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

public class ItemInit {
	
	public static final DeferredRegister<Item> ITEMS = new DeferredRegister<>(ForgeRegistries.ITEMS, HardmodeMod.MOD_ID);
	
	public static final RegistryObject<Item> SHADOW_CORE_ITEM = ITEMS.register("shadow_core_item", () -> new ShadowCoreItem(new Item.Properties().group(HardmodeItemGroup.instance).maxStackSize(1)));
	public static final RegistryObject<Item> ENDER_DRAGON_ESSENCE = ITEMS.register("ender_dragon_essence", () -> new EnderDragonEssence(new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> SHADOW_ESSENCE = ITEMS.register("shadow_essence", () -> new ShadowEssence(new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> DRAGON_SWORD = ITEMS.register("dragon_sword", () -> new DragonSword(HardmodeItemTier.DRAGON, 3, -2.4F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> DRAGON_PICKAXE = ITEMS.register("dragon_pickaxe", () -> new DragonPickaxe(HardmodeItemTier.DRAGON, 1, -2.8F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> PALLADIUM_INGOT = ITEMS.register("palladium_ingot", () -> new PalladiumIngot(new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> ORICHALCUM_INGOT = ITEMS.register("orichalcum_ingot", () -> new OrichalcumIngot(new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> ADAMANTITE_INGOT = ITEMS.register("adamantite_ingot", () -> new AdamantiteIngot(new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> PALLADIUM_ROD = ITEMS.register("palladium_rod", () -> new PalladiumRod(new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> ORICHALCUM_ROD = ITEMS.register("orichalcum_rod", () -> new OrichalcumRod(new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> ADAMANTITE_ROD = ITEMS.register("adamantite_rod", () -> new AdamantiteRod(new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> PALLADIUM_SWORD = ITEMS.register("palladium_sword", () -> new PalladiumSword(HardmodeItemTier.PALLADIUM, 3, -2.4F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> PALLADIUM_PICKAXE = ITEMS.register("palladium_pickaxe", () -> new PalladiumPickaxe(HardmodeItemTier.PALLADIUM, 1, -2.8F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> PALLADIUM_WARAXE = ITEMS.register("palladium_waraxe", () -> new PalladiumWaraxe(HardmodeItemTier.PALLADIUM, 8, -3.0F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> PALLADIUM_SHOVEL = ITEMS.register("palladium_shovel", () -> new PalladiumShovel(HardmodeItemTier.PALLADIUM, 1, -3.0F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> PALLADIUM_HOE = ITEMS.register("palladium_hoe", () -> new PalladiumHoe(HardmodeItemTier.PALLADIUM, 0.0F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> ORICHALCUM_SWORD = ITEMS.register("orichalcum_sword", () -> new OrichalcumSword(HardmodeItemTier.ORICHALCUM, 3, -2.4F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> ORICHALCUM_PICKAXE = ITEMS.register("orichalcum_pickaxe", () -> new OrichalcumPickaxe(HardmodeItemTier.ORICHALCUM, 1, -2.8F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> ORICHALCUM_WARAXE = ITEMS.register("orichalcum_waraxe", () -> new OrichalcumWaraxe(HardmodeItemTier.ORICHALCUM, 8, -3.0F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> ORICHALCUM_SHOVEL = ITEMS.register("orichalcum_shovel", () -> new OrichalcumShovel(HardmodeItemTier.ORICHALCUM, 1, -3.0F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> ORICHALCUM_HOE = ITEMS.register("orichalcum_hoe", () -> new OrichalcumHoe(HardmodeItemTier.ORICHALCUM, 0.0F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> ADAMANTITE_SWORD = ITEMS.register("adamantite_sword", () -> new AdamantiteSword(HardmodeItemTier.ADAMANTITE, 3, -2.4F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> ADAMANTITE_PICKAXE = ITEMS.register("adamantite_pickaxe", () -> new AdamantitePickaxe(HardmodeItemTier.ADAMANTITE, 1, -2.8F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> ADAMANTITE_WARAXE = ITEMS.register("adamantite_waraxe", () -> new AdamantiteWaraxe(HardmodeItemTier.ADAMANTITE, 8, -3.0F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> ADAMANTITE_SHOVEL = ITEMS.register("adamantite_shovel", () -> new AdamantiteShovel(HardmodeItemTier.ADAMANTITE, 1, -3.0F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> ADAMANTITE_HOE = ITEMS.register("adamantite_hoe", () -> new AdamantiteHoe(HardmodeItemTier.ADAMANTITE, 0.0F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> PALLADIUM_HELMET = ITEMS.register("palladium_helmet", () -> new PalladiumArmor(HardmodeArmorMaterial.PALLADIUM, EquipmentSlotType.HEAD, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> PALLADIUM_CHESTPLATE = ITEMS.register("palladium_chestplate", () -> new PalladiumArmor(HardmodeArmorMaterial.PALLADIUM, EquipmentSlotType.CHEST, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> PALLADIUM_LEGGINGS = ITEMS.register("palladium_leggings", () -> new PalladiumArmor(HardmodeArmorMaterial.PALLADIUM, EquipmentSlotType.LEGS, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> PALLADIUM_BOOTS = ITEMS.register("palladium_boots", () -> new PalladiumArmor(HardmodeArmorMaterial.PALLADIUM, EquipmentSlotType.FEET, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> ORICHALCUM_HELMET = ITEMS.register("orichalcum_helmet", () -> new OrichalcumArmor(HardmodeArmorMaterial.ORICHALCUM, EquipmentSlotType.HEAD, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> ORICHALCUM_CHESTPLATE = ITEMS.register("orichalcum_chestplate", () -> new OrichalcumArmor(HardmodeArmorMaterial.ORICHALCUM, EquipmentSlotType.CHEST, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> ORICHALCUM_LEGGINGS = ITEMS.register("orichalcum_leggings", () -> new OrichalcumArmor(HardmodeArmorMaterial.ORICHALCUM, EquipmentSlotType.LEGS, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> ORICHALCUM_BOOTS = ITEMS.register("orichalcum_boots", () -> new OrichalcumArmor(HardmodeArmorMaterial.ORICHALCUM, EquipmentSlotType.FEET, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> ADAMANTITE_HELMET = ITEMS.register("adamantite_helmet", () -> new AdamantiteArmor(HardmodeArmorMaterial.ADAMANTITE, EquipmentSlotType.HEAD, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> ADAMANTITE_CHESTPLATE = ITEMS.register("adamantite_chestplate", () -> new AdamantiteArmor(HardmodeArmorMaterial.ADAMANTITE, EquipmentSlotType.CHEST, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> ADAMANTITE_LEGGINGS = ITEMS.register("adamantite_leggings", () -> new AdamantiteArmor(HardmodeArmorMaterial.ADAMANTITE, EquipmentSlotType.LEGS, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> ADAMANTITE_BOOTS = ITEMS.register("adamantite_boots", () -> new AdamantiteArmor(HardmodeArmorMaterial.ADAMANTITE, EquipmentSlotType.FEET, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> STAR_FRAGMENT = ITEMS.register("star_fragment", () -> new StarFragment(new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> SUPER_STAR = ITEMS.register("super_star", () -> new SuperStar(new Item.Properties().group(HardmodeItemGroup.instance).maxStackSize(8)));
	public static final RegistryObject<Item> RED_LIGHTSABER = ITEMS.register("red_lightsaber", () -> new RedLightsaber(HardmodeItemTier.LIGHTSABER, 4, -2.4F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> YELLOW_LIGHTSABER = ITEMS.register("yellow_lightsaber", () -> new YellowLightsaber(HardmodeItemTier.LIGHTSABER, 3, -2.0F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> GREEN_LIGHTSABER = ITEMS.register("green_lightsaber", () -> new GreenLightsaber(HardmodeItemTier.LIGHTSABER, 3, -2.4F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> BLUE_LIGHTSABER = ITEMS.register("blue_lightsaber", () -> new BlueLightsaber(HardmodeItemTier.LIGHTSABER, 3, -2.4F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> PURPLE_LIGHTSABER = ITEMS.register("purple_lightsaber", () -> new PurpleLightsaber(HardmodeItemTier.LIGHTSABER, 3, -2.4F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> WHITE_LIGHTSABER = ITEMS.register("white_lightsaber", () -> new WhiteLightsaber(HardmodeItemTier.LIGHTSABER, 3, -2.4F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> ENLIGHTENMENT_PICKAXE = ITEMS.register("enlightenment_pickaxe", () -> new EnlightenmentPickaxe(HardmodeItemTier.STAR_PICK, 1, -2.8F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> MOLTEN_BAR = ITEMS.register("molten_bar", () -> new MoltenBar(new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> HELLSTONE_CHUNK = ITEMS.register("hellstone_chunk", () -> new HellstoneChunk(new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> MOLTEN_ROD = ITEMS.register("molten_rod", () -> new MoltenRod(new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> MOLTEN_SWORD = ITEMS.register("molten_sword", () -> new MoltenSword(HardmodeItemTier.MOLTEN, 3, -2.4F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> MOLTEN_PICKAXE = ITEMS.register("molten_pickaxe", () -> new MoltenPickaxe(HardmodeItemTier.MOLTEN, 1, -2.8F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> MOLTEN_WARAXE = ITEMS.register("molten_waraxe", () -> new MoltenWaraxe(HardmodeItemTier.MOLTEN, 8, -3.0F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> MOLTEN_SHOVEL = ITEMS.register("molten_shovel", () -> new MoltenShovel(HardmodeItemTier.MOLTEN, 1, -3.0F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> MOLTEN_HOE = ITEMS.register("molten_hoe", () -> new MoltenHoe(HardmodeItemTier.MOLTEN, 0.0F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> MOLTEN_HELMET = ITEMS.register("molten_helmet", () -> new MoltenArmor(HardmodeArmorMaterial.MOLTEN, EquipmentSlotType.HEAD, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> MOLTEN_CHESTPLATE = ITEMS.register("molten_chestplate", () -> new MoltenArmor(HardmodeArmorMaterial.MOLTEN, EquipmentSlotType.CHEST, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> MOLTEN_LEGGINGS = ITEMS.register("molten_leggings", () -> new MoltenArmor(HardmodeArmorMaterial.MOLTEN, EquipmentSlotType.LEGS, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> MOLTEN_BOOTS = ITEMS.register("molten_boots", () -> new MoltenArmor(HardmodeArmorMaterial.MOLTEN, EquipmentSlotType.FEET, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> MOLTEN_CORE= ITEMS.register("molten_core", () -> new MoltenCore(new Item.Properties().group(HardmodeItemGroup.instance).maxStackSize(8)));
	public static final RegistryObject<Item> DRAGON_HELMET = ITEMS.register("dragon_helmet", () -> new DragonArmor(HardmodeArmorMaterial.DRAGON, EquipmentSlotType.HEAD, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> DRAGON_CHESTPLATE = ITEMS.register("dragon_chestplate", () -> new DragonArmor(HardmodeArmorMaterial.DRAGON, EquipmentSlotType.CHEST, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> DRAGON_LEGGINGS = ITEMS.register("dragon_leggings", () -> new DragonArmor(HardmodeArmorMaterial.DRAGON, EquipmentSlotType.LEGS, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> DRAGON_BOOTS = ITEMS.register("dragon_boots", () -> new DragonArmor(HardmodeArmorMaterial.DRAGON, EquipmentSlotType.FEET, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> GELATIN_CRYSTAL = ITEMS.register("gelatin_crystal", () -> new GelatinCrystal(new Item.Properties().group(HardmodeItemGroup.instance).food(new Food.Builder().hunger(10).saturation(2.4F).fastToEat().build())));
	public static final RegistryObject<Item> CRYSTAL_SHARD = ITEMS.register("crystal_shard", () -> new CrystalShard(new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> CRYSTAL_APPLE = ITEMS.register("crystal_apple", () -> new CrystalApple(new Item.Properties().group(HardmodeItemGroup.instance).food(new Food.Builder().hunger(4).saturation(2.4F).setAlwaysEdible().build())));
	public static final RegistryObject<Item> UNPOWERED_RGB_LIGHTSABER = ITEMS.register("unpowered_rgb_lightsaber", () -> new UnpoweredRgbLightsaber(new Item.Properties().group(HardmodeItemGroup.instance).maxStackSize(1)));
	public static final RegistryObject<Item> TRUE_RGB_LIGHTSABER = ITEMS.register("true_rgb_lightsaber", () -> new TrueRgbLightsaber(HardmodeItemTier.RGB_LIGHTSABER, 3, -2.0F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> MOON_STONE = ITEMS.register("moon_stone", () -> new MoonStone(new Item.Properties().group(HardmodeItemGroup.instance).maxStackSize(1)));
	public static final RegistryObject<Item> DEATH_SCYTHE = ITEMS.register("death_scythe", () -> new DeathScythe(HardmodeItemTier.DEATH_SCYTHE, 3, -2.4F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> PSYCHO_KNIFE = ITEMS.register("psycho_knife", () -> new PsychoKnife(HardmodeItemTier.PSYCHO_KNIFE, 3, -1.4F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> KATANA = ITEMS.register("katana", () -> new Katana(HardmodeItemTier.KATANA, 3, -2.0F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> TRUE_DRAGON_BLADE = ITEMS.register("true_dragon_blade", () -> new TrueDragonBlade(HardmodeItemTier.DRAGON_BLADE, 3, -2.0F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> SHADOW_CAPE = ITEMS.register("shadow_cape", () -> new ShadowCape(HardmodeArmorMaterial.SHADOW_CAPE, EquipmentSlotType.CHEST, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> LIFE_CRYSTAL = ITEMS.register("life_crystal", () -> new LifeCrystal(new Item.Properties().group(HardmodeItemGroup.instance).maxStackSize(10).food(new Food.Builder().hunger(3).saturation(1.2F).fastToEat().setAlwaysEdible().build())));
	public static final RegistryObject<Item> CORE_OF_PEACE = ITEMS.register("core_of_peace", () -> new CoreOfPeace(new Item.Properties().group(HardmodeItemGroup.instance).maxStackSize(1)));
	public static final RegistryObject<Item> NANO_BOOST = ITEMS.register("nano_boost", () -> new NanoBoost(new Item.Properties().group(HardmodeItemGroup.instance).maxStackSize(8)));
	public static final RegistryObject<Item> NANO_BLADE = ITEMS.register("nano_blade", () -> new NanoBlade(HardmodeItemTier.NANO_BLADE, 3, -2.0F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> BLAZING_SKULL = ITEMS.register("blazing_skull", () -> new BlazingSkull(new Item.Properties().group(HardmodeItemGroup.instance).maxStackSize(1)));
	public static final RegistryObject<Item> SUPER_STRING = ITEMS.register("super_string", () -> new SuperString(new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> PALLADIUM_REPEATER = ITEMS.register("palladium_repeater", () -> new PalladiumRepeater(new Item.Properties().group(HardmodeItemGroup.instance).maxStackSize(1)));
	public static final RegistryObject<Item> ORICHALCUM_REPEATER = ITEMS.register("orichalcum_repeater", () -> new OrichalcumRepeater(new Item.Properties().group(HardmodeItemGroup.instance).maxStackSize(1)));
	public static final RegistryObject<Item> ADAMANTITE_REPEATER = ITEMS.register("adamantite_repeater", () -> new AdamantiteRepeater(new Item.Properties().group(HardmodeItemGroup.instance).maxStackSize(1)));
	public static final RegistryObject<Item> MOLTEN_REPEATER = ITEMS.register("molten_repeater", () -> new MoltenRepeater(new Item.Properties().group(HardmodeItemGroup.instance).maxStackSize(1)));
	public static final RegistryObject<Item> WARP_STAR = ITEMS.register("warp_star", () -> new WarpStar(new Item.Properties().group(HardmodeItemGroup.instance).maxStackSize(8)));
	public static final RegistryObject<Item> MAGIC_MIRROR = ITEMS.register("magic_mirror", () -> new MagicMirror(new Item.Properties().group(HardmodeItemGroup.instance).maxStackSize(1)));
	public static final RegistryObject<Item> SHATTERED_MAGIC_MIRROR = ITEMS.register("shattered_magic_mirror", () -> new ShatteredMagicMirror(new Item.Properties().group(HardmodeItemGroup.instance).maxStackSize(1)));
	public static final RegistryObject<Item> INSTANT_HEALING_POTION = ITEMS.register("instant_healing_potion", () -> new InstantHealingPotion(new Item.Properties().group(HardmodeItemGroup.instance).maxStackSize(16)));
	public static final RegistryObject<Item> EYE_OF_CTHULHU_TREASURE_BAG = ITEMS.register("eye_of_cthulhu_treasure_bag", () -> new EyeOfCthulhuTreasureBag(new Item.Properties().group(HardmodeItemGroup.instance).maxStackSize(1)));
	public static final RegistryObject<Item> LENS = ITEMS.register("lens", () -> new Lens(new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> SUSPICIOUS_LOOKING_EYE = ITEMS.register("suspicious_looking_eye", () -> new SuspiciousLookingEye(new Item.Properties().group(HardmodeItemGroup.instance).maxStackSize(8)));
	public static final RegistryObject<Item> CHLOROPHYTE_BAR = ITEMS.register("chlorophyte_bar", () -> new ChlorophyteBar(new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> CHLOROPHYTE_CHUNK = ITEMS.register("chlorophyte_chunk", () -> new ChlorophyteChunk(new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> CHLOROPHYTE_SWORD = ITEMS.register("chlorophyte_sword", () -> new ChlorophyteSword(HardmodeItemTier.CHLOROPHYTE, 3, -2.4F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> CHLOROPHYTE_PICKAXE = ITEMS.register("chlorophyte_pickaxe", () -> new ChlorophytePickaxe(HardmodeItemTier.CHLOROPHYTE, 1, -2.8F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> CHLOROPHYTE_WARAXE = ITEMS.register("chlorophyte_waraxe", () -> new ChlorophyteWaraxe(HardmodeItemTier.CHLOROPHYTE, 8, -3.0F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> CHLOROPHYTE_SHOVEL = ITEMS.register("chlorophyte_shovel", () -> new ChlorophyteShovel(HardmodeItemTier.CHLOROPHYTE, 1, -3.0F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> CHLOROPHYTE_HOE = ITEMS.register("chlorophyte_hoe", () -> new ChlorophyteHoe(HardmodeItemTier.CHLOROPHYTE, 0.0F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> CHLOROPHYTE_HELMET = ITEMS.register("chlorophyte_helmet", () -> new ChlorophyteArmor(HardmodeArmorMaterial.CHLOROPHYTE, EquipmentSlotType.HEAD, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> CHLOROPHYTE_CHESTPLATE = ITEMS.register("chlorophyte_chestplate", () -> new ChlorophyteArmor(HardmodeArmorMaterial.CHLOROPHYTE, EquipmentSlotType.CHEST, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> CHLOROPHYTE_LEGGINGS = ITEMS.register("chlorophyte_leggings", () -> new ChlorophyteArmor(HardmodeArmorMaterial.CHLOROPHYTE, EquipmentSlotType.LEGS, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> CHLOROPHYTE_BOOTS = ITEMS.register("chlorophyte_boots", () -> new ChlorophyteArmor(HardmodeArmorMaterial.CHLOROPHYTE, EquipmentSlotType.FEET, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> CHLOROPHYTE_REPEATER = ITEMS.register("chlorophyte_repeater", () -> new ChlorophyteRepeater(new Item.Properties().group(HardmodeItemGroup.instance).maxStackSize(1)));
	public static final RegistryObject<Item> CRIMSON_ESSENCE = ITEMS.register("crimson_essence", () -> new CrimsonEssence(new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> CRIMSON_BLADE = ITEMS.register("crimson_blade", () -> new CrimsonBlade(HardmodeItemTier.CRIMSON, 3, -2.4F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> CRIMSON_PICKAXE = ITEMS.register("crimson_pickaxe", () -> new CrimsonPickaxe(HardmodeItemTier.CRIMSON, 1, -2.8F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> HARDMODE_MEDALLION = ITEMS.register("hardmode_medallion", () -> new HardmodeMedallion(new Item.Properties().group(HardmodeItemGroup.instance).maxStackSize(1)));
	public static final RegistryObject<Item> LIFE_BAND = ITEMS.register("life_band", () -> new LifeBand(new Item.Properties().group(HardmodeItemGroup.instance).maxStackSize(1)));
	public static final RegistryObject<Item> SUN_STONE = ITEMS.register("sun_stone", () -> new SunStone(new Item.Properties().group(HardmodeItemGroup.instance).maxStackSize(1)));
	public static final RegistryObject<Item> CELESTIAL_STONE = ITEMS.register("celestial_stone", () -> new CelestialStone(new Item.Properties().group(HardmodeItemGroup.instance).maxStackSize(1)));
	public static final RegistryObject<Item> MOLTEN_SKULL_BAND = ITEMS.register("molten_skull_band", () -> new MoltenSkullBand(new Item.Properties().group(HardmodeItemGroup.instance).maxStackSize(1)));
	public static final RegistryObject<Item> BLOODY_VERTEBRA = ITEMS.register("bloody_vertebra", () -> new BloodyVertebra(new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> BLOODY_VERTEBRA_MASK = ITEMS.register("bloody_vertebra_mask", () -> new BloodyVertebraArmor(HardmodeArmorMaterial.BLOODY_VERTEBRA, EquipmentSlotType.HEAD, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> BLOODY_VERTEBRA_TORSO = ITEMS.register("bloody_vertebra_torso", () -> new BloodyVertebraArmor(HardmodeArmorMaterial.BLOODY_VERTEBRA, EquipmentSlotType.CHEST, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> BLOODY_VERTEBRA_LEGGINGS = ITEMS.register("bloody_vertebra_leggings", () -> new BloodyVertebraArmor(HardmodeArmorMaterial.BLOODY_VERTEBRA, EquipmentSlotType.LEGS, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> BLOODY_VERTEBRA_BOOTS = ITEMS.register("bloody_vertebra_boots", () -> new BloodyVertebraArmor(HardmodeArmorMaterial.BLOODY_VERTEBRA, EquipmentSlotType.FEET, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> INFERNAL_HAMMER = ITEMS.register("infernal_hammer", () -> new InfernalHammer(HardmodeItemTier.INFERNAL_HAMMER, 3, -3.0F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> EMERALD_SWORD = ITEMS.register("emerald_sword", () -> new EmeraldSword(HardmodeItemTier.EMERALD, 3, -2.4F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> EMERALD_PICKAXE = ITEMS.register("emerald_pickaxe", () -> new EmeraldPickaxe(HardmodeItemTier.EMERALD, 1, -2.8F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> EMERALD_WARAXE = ITEMS.register("emerald_waraxe", () -> new EmeraldWaraxe(HardmodeItemTier.EMERALD, 7, -3.0F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> EMERALD_HELMET = ITEMS.register("emerald_helmet", () -> new EmeraldArmor(HardmodeArmorMaterial.EMERALD, EquipmentSlotType.HEAD, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> EMERALD_CHESTPLATE = ITEMS.register("emerald_chestplate", () -> new EmeraldArmor(HardmodeArmorMaterial.EMERALD, EquipmentSlotType.CHEST, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> EMERALD_LEGGINGS = ITEMS.register("emerald_leggings", () -> new EmeraldArmor(HardmodeArmorMaterial.EMERALD, EquipmentSlotType.LEGS, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> EMERALD_BOOTS = ITEMS.register("emerald_boots", () -> new EmeraldArmor(HardmodeArmorMaterial.EMERALD, EquipmentSlotType.FEET, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> TITAN_RING = ITEMS.register("titan_ring", () -> new TitanRing(new Item.Properties().group(HardmodeItemGroup.instance).maxStackSize(1)));

	
	public static final RegistryObject<HardmodeSpawnEgg> SUPER_ZOMBIE_SPAWN_EGG = ITEMS.register("super_zombie_spawn_egg", () -> new HardmodeSpawnEgg(HardmodeEntityTypes.SUPER_ZOMBIE, 0x007C7C, 0xFF2F2F, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<HardmodeSpawnEgg> WEREWOLF_SPAWN_EGG = ITEMS.register("werewolf_spawn_egg", () -> new HardmodeSpawnEgg(HardmodeEntityTypes.WEREWOLF, 0x203248, 0x597CA4, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<HardmodeSpawnEgg> PSYCHO_SPAWN_EGG = ITEMS.register("psycho_spawn_egg", () -> new HardmodeSpawnEgg(HardmodeEntityTypes.PSYCHO, 0x4B3411, 0x55000C, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<HardmodeSpawnEgg> REAPER_SPAWN_EGG = ITEMS.register("reaper_spawn_egg", () -> new HardmodeSpawnEgg(HardmodeEntityTypes.REAPER, 0x0D0D0D, 0xA349A4, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<HardmodeSpawnEgg> PLAYER_ASSASSIN_SPAWN_EGG = ITEMS.register("player_assassin_spawn_egg", () -> new HardmodeSpawnEgg(HardmodeEntityTypes.PLAYER_ASSASSIN, 0x191513, 0xBFBAB4, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<HardmodeSpawnEgg> TITAN_SPAWN_EGG = ITEMS.register("titan_spawn_egg", () -> new HardmodeSpawnEgg(HardmodeEntityTypes.TITAN, 0xFFD6B3, 0xC59579, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<HardmodeSpawnEgg> FIRE_DEMON_SPAWN_EGG = ITEMS.register("fire_demon_spawn_egg", () -> new HardmodeSpawnEgg(HardmodeEntityTypes.FIRE_DEMON, 0xE73706, 0xF7CF01, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<HardmodeSpawnEgg> SUPER_SPIDER_SPAWN_EGG = ITEMS.register("super_spider_spawn_egg", () -> new HardmodeSpawnEgg(HardmodeEntityTypes.SUPER_SPIDER, 0x00796A, 0x5EFFF6, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<HardmodeSpawnEgg> DEMON_EYE_SPAWN_EGG = ITEMS.register("demon_eye_spawn_egg", () -> new HardmodeSpawnEgg(HardmodeEntityTypes.DEMON_EYE, 0xE7E7E7, 0xD91919, new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<HardmodeSpawnEgg> FACE_MONSTER_SPAWN_EGG = ITEMS.register("face_monster_spawn_egg", () -> new HardmodeSpawnEgg(HardmodeEntityTypes.FACE_MONSTER, 0x734945, 0x7C0000, new Item.Properties().group(HardmodeItemGroup.instance)));

	
	public static final RegistryObject<Item> SHADOW_CORE_BLOCK = ITEMS.register("shadow_core_block", () -> new ShadowCoreBlock(BlockInit.SHADOW_CORE_BLOCK.get(), new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> CRYSTAL_SEEDS = ITEMS.register("crystal_seeds", () -> new CrystalSeeds(BlockInit.CRYSTAL_CROPS.get(), new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> PALLADIUM_ORE = ITEMS.register("palladium_ore", () -> new PalladiumOre(BlockInit.PALLADIUM_ORE.get(), new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> ORICHALCUM_ORE = ITEMS.register("orichalcum_ore", () -> new OrichalcumOre(BlockInit.ORICHALCUM_ORE.get(), new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> ADAMANTITE_ORE = ITEMS.register("adamantite_ore", () -> new AdamantiteOre(BlockInit.ADAMANTITE_ORE.get(), new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> PALLADIUM_BLOCK = ITEMS.register("palladium_block", () -> new PalladiumBlock(BlockInit.PALLADIUM_BLOCK.get(), new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> ORICHALCUM_BLOCK = ITEMS.register("orichalcum_block", () -> new OrichalcumBlock(BlockInit.ORICHALCUM_BLOCK.get(), new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> ADAMANTITE_BLOCK = ITEMS.register("adamantite_block", () -> new AdamantiteBlock(BlockInit.ADAMANTITE_BLOCK.get(), new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> STAR_CHUNK = ITEMS.register("star_chunk", () -> new StarChunk(BlockInit.STAR_CHUNK.get(), new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> HELLSTONE = ITEMS.register("hellstone", () -> new Hellstone(BlockInit.HELLSTONE.get(), new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> MOLTEN_BLOCK = ITEMS.register("molten_block", () -> new MoltenBlock(BlockInit.MOLTEN_BLOCK.get(), new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> HARDMODE_BLOCK = ITEMS.register("hardmode_block", () -> new HardmodeBlock(BlockInit.HARDMODE_BLOCK.get(), new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> CHLOROPHYTE_ORE = ITEMS.register("chlorophyte_ore", () -> new ChlorophyteOre(BlockInit.CHLOROPHYTE_ORE.get(), new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> CHLOROPHYTE_BLOCK = ITEMS.register("chlorophyte_block", () -> new ChlorophyteBlock(BlockInit.CHLOROPHYTE_BLOCK.get(), new Item.Properties().group(HardmodeItemGroup.instance)));
	public static final RegistryObject<Item> CHLOROSEEDS = ITEMS.register("chloroseeds", () -> new CrystalSeeds(BlockInit.CHLOROCROPS.get(), new Item.Properties().group(HardmodeItemGroup.instance)));

	
}
